### ISSUE TITLE
Is not compatible with brew installed GNU findutils

### ISSUE THREAD

**Issue by chenhouwu** [kivy/kivy-sdk-packager#27]
the GNU find has no option of ` -E`

**Comment by chenhouwu** [comment]
after switch back to use `/usr/bin/find`, I got the following error:

```
rm: Binary file (standard input) matches
: No such file or directory
Traceback (most recent call last):
  File "package_app.py", line 234, in <module>
    main(arguments)
  File "package_app.py", line 223, in main
    compile_app(appname)
  File "package_app.py", line 167, in compile_app
    shell=True)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/find -E myapp.app -regex "(.*)\\.py" -print0 | grep -v __init__ | xargs -0 rm']' returned non-zero exit status 123
```
